server:
  port: 56888
  context-path: /investing

logging:
  file: log/robo-investing.log
  level: INFO

spring:
  properties.hibernate.format_sql: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate #auto-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

robo-investing:
  data-loader:
    enabled: false
    nasdaq-file:
    nyse-file:
