server:
  port: 56700
  context-path: /investing/dataloader

logging:
  file: log/investing-data-loader.log
  level: INFO

spring:
  profiles:
    active: sensitive
  properties.hibernate.format_sql: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate #auto-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

nevex-investing:
  ticker-data-loader:
    enabled: false # Set this to true and and put values in below for the optional csv to load data into the database
    nasdaq-file: D:\Coding\Git\nevex_investing\data\nasdaq_tickers_08_07_2017.csv
    nyse-file: D:\Coding\Git\nevex_investing\data\nyse_tickers_08_07_2017.csv
  stock-historical-loader:
    enabled: false
    wait-time-between-tickers-ms: 1000
  daily-stock-price-loader:
    enabled: true
    wait-time-between-tickers-ms: 1000
    force-start-on-activation: false
  tiingo:
    host: https://api.tiingo.com
  testing:
    enabled: false
    allowed-symbols: LC, NVDA, FB, APPL, NAKD, GOOGL, MSFT

# Tiingo API: https://api.tiingo.com/

