

SET search_path TO investing;
delete from analyzer_weights_v1;

insert into analyzer_weights_v1("name", "start", "end", "weight")
values
-- Fundamentals
('price-to-earnings-ratio', -10000, -30, -1.0),
('price-to-earnings-ratio', -30, -10, -0.6),
('price-to-earnings-ratio', -10, 0.001, -0.3),
('price-to-earnings-ratio', 0.001, 0.01, 0),
('price-to-earnings-ratio', 0.01, 5, 0.8),
('price-to-earnings-ratio', 5, 10, 0.7),
('price-to-earnings-ratio', 10, 20, 0.6),
('price-to-earnings-ratio', 20, 30, 0.5),
('price-to-earnings-ratio', 30, 50, 0.4),
('price-to-earnings-ratio', 50, 10000, 0.1),

('earnings-per-share', -10000, -20, -1.0),
('earnings-per-share', -20, -1, -0.7),
('earnings-per-share', -1, 0, -0.3),
('earnings-per-share', 0, 1, 0.1),
('earnings-per-share', 1, 5, 0.2),
('earnings-per-share', 5, 10, 0.3),
('earnings-per-share', 10, 20, 0.4),
('earnings-per-share', 20, 50, 0.5),
('earnings-per-share', 50, 1000000, 0.6),

-- Summary of analyzers
('analyzer-summary-counter-adjust-weight', 0, 5, 0.05),
('analyzer-summary-counter-adjust-weight', 5, 10, 0.1),
('analyzer-summary-counter-adjust-weight', 10, 20, 0.15),
('analyzer-summary-counter-adjust-weight', 20, 50, 0.2),
('analyzer-summary-counter-adjust-weight', 50, 100000, 0.22),

----------------------------------------------------------
--- 1 Day analyzers
----------------------------------------------------------
('current-stock-price-compared-to-1-day-previous-close-average-percent-deviation', -10000.0, -1.0, 1.0),
('current-stock-price-compared-to-1-day-previous-close-average-percent-deviation', -1.00, -0.70, 0.9),
('current-stock-price-compared-to-1-day-previous-close-average-percent-deviation', -0.70, -0.40, 0.8),
('current-stock-price-compared-to-1-day-previous-close-average-percent-deviation', -0.40, -0.20, 0.7),
('current-stock-price-compared-to-1-day-previous-close-average-percent-deviation', -0.20, -0.10, 0.6),
('current-stock-price-compared-to-1-day-previous-close-average-percent-deviation', -0.10, -0.05, 0.5),
('current-stock-price-compared-to-1-day-previous-close-average-percent-deviation', -0.05, -0.02, 0.4),
('current-stock-price-compared-to-1-day-previous-close-average-percent-deviation', -0.02, -0.01, 0.2),
('current-stock-price-compared-to-1-day-previous-close-average-percent-deviation', -0.01, 0.00, 0.1),
('current-stock-price-compared-to-1-day-previous-close-average-percent-deviation', 0.00, 0.05, -0.1),
('current-stock-price-compared-to-1-day-previous-close-average-percent-deviation', 0.05, 0.1, -0.2),
('current-stock-price-compared-to-1-day-previous-close-average-percent-deviation', 0.1, 0.2, -0.5),
('current-stock-price-compared-to-1-day-previous-close-average-percent-deviation', 0.2, 1000000, -1.0),

('current-stock-price-compared-to-1-day-previous-high-average-percent-deviation', -10000.0, -1.0, 1.0),
('current-stock-price-compared-to-1-day-previous-high-average-percent-deviation', -1.00, -0.70, 0.9),
('current-stock-price-compared-to-1-day-previous-high-average-percent-deviation', -0.70, -0.40, 0.8),
('current-stock-price-compared-to-1-day-previous-high-average-percent-deviation', -0.40, -0.20, 0.7),
('current-stock-price-compared-to-1-day-previous-high-average-percent-deviation', -0.20, -0.10, 0.6),
('current-stock-price-compared-to-1-day-previous-high-average-percent-deviation', -0.10, -0.05, 0.5),
('current-stock-price-compared-to-1-day-previous-high-average-percent-deviation', -0.05, -0.02, 0.4),
('current-stock-price-compared-to-1-day-previous-high-average-percent-deviation', -0.02, -0.01, 0.2),
('current-stock-price-compared-to-1-day-previous-high-average-percent-deviation', -0.01, 0.00, 0.1),
('current-stock-price-compared-to-1-day-previous-high-average-percent-deviation', 0.00, 0.05, -0.1),
('current-stock-price-compared-to-1-day-previous-high-average-percent-deviation', 0.05, 0.1, -0.2),
('current-stock-price-compared-to-1-day-previous-high-average-percent-deviation', 0.1, 0.2, -0.5),
('current-stock-price-compared-to-1-day-previous-high-average-percent-deviation', 0.2, 1000000, -1.0),

('current-stock-price-compared-to-1-day-previous-low-average-percent-deviation', -10000.0, -1.0, 1.0),
('current-stock-price-compared-to-1-day-previous-low-average-percent-deviation', -1.00, -0.70, 0.9),
('current-stock-price-compared-to-1-day-previous-low-average-percent-deviation', -0.70, -0.40, 0.8),
('current-stock-price-compared-to-1-day-previous-low-average-percent-deviation', -0.40, -0.20, 0.7),
('current-stock-price-compared-to-1-day-previous-low-average-percent-deviation', -0.20, -0.10, 0.6),
('current-stock-price-compared-to-1-day-previous-low-average-percent-deviation', -0.10, -0.05, 0.5),
('current-stock-price-compared-to-1-day-previous-low-average-percent-deviation', -0.05, -0.02, 0.4),
('current-stock-price-compared-to-1-day-previous-low-average-percent-deviation', -0.02, -0.01, 0.2),
('current-stock-price-compared-to-1-day-previous-low-average-percent-deviation', -0.01, 0.00, 0.1),
('current-stock-price-compared-to-1-day-previous-low-average-percent-deviation', 0.00, 0.05, -0.1),
('current-stock-price-compared-to-1-day-previous-low-average-percent-deviation', 0.05, 0.1, -0.2),
('current-stock-price-compared-to-1-day-previous-low-average-percent-deviation', 0.1, 0.2, -0.5),
('current-stock-price-compared-to-1-day-previous-low-average-percent-deviation', 0.2, 1000000, -1.0),

('current-stock-price-compared-to-1-day-previous-lowest-percent-deviation', -10000.0, -1.0, 1.0),
('current-stock-price-compared-to-1-day-previous-lowest-percent-deviation', -1.00, -0.30, 1.0),
('current-stock-price-compared-to-1-day-previous-lowest-percent-deviation', -0.30, -0.10, 0.5),
('current-stock-price-compared-to-1-day-previous-lowest-percent-deviation', -0.10, -0.001, 0.2),
('current-stock-price-compared-to-1-day-previous-lowest-percent-deviation', -0.001, 0.0, 0.1),
('current-stock-price-compared-to-1-day-previous-lowest-percent-deviation', 0.0, 0.1, -0.05),
('current-stock-price-compared-to-1-day-previous-lowest-percent-deviation', 0.1, 0.4, -0.4),
('current-stock-price-compared-to-1-day-previous-lowest-percent-deviation', 0.4, 1000000, -1.0),

('current-stock-price-compared-to-1-day-previous-highest-percent-deviation', -10000.0, -1.0, 1.0),
('current-stock-price-compared-to-1-day-previous-highest-percent-deviation', -1.00, -0.80, 1.0),
('current-stock-price-compared-to-1-day-previous-highest-percent-deviation', -0.80, 0.0, 0.1),
('current-stock-price-compared-to-1-day-previous-highest-percent-deviation', 0.0, 0.4, -0.6),
('current-stock-price-compared-to-1-day-previous-highest-percent-deviation', 0.4, 1000000, -1.0),

('current-lowest-stock-price-compared-to-1-day-previous-lowest-percent-deviation', -10000.0, -8.0, 1.0),
('current-lowest-stock-price-compared-to-1-day-previous-lowest-percent-deviation', -0.80, -0.3, 0.6),
('current-lowest-stock-price-compared-to-1-day-previous-lowest-percent-deviation', -0.3, 0.0, 0.4),
('current-lowest-stock-price-compared-to-1-day-previous-lowest-percent-deviation', 0.0, 0.1, -0.1),
('current-lowest-stock-price-compared-to-1-day-previous-lowest-percent-deviation', 0.1, 0.4, -0.3),
('current-lowest-stock-price-compared-to-1-day-previous-lowest-percent-deviation', 0.4, 1000000, -0.8),

('current-lowest-stock-price-compared-to-1-day-previous-low-average-percent-deviation', -10000.0, -8.0, 1.0),
('current-lowest-stock-price-compared-to-1-day-previous-low-average-percent-deviation', -0.80, -0.3, 0.6),
('current-lowest-stock-price-compared-to-1-day-previous-low-average-percent-deviation', -0.3, 0.0, 0.4),
('current-lowest-stock-price-compared-to-1-day-previous-low-average-percent-deviation', 0.0, 0.1, -0.1),
('current-lowest-stock-price-compared-to-1-day-previous-low-average-percent-deviation', 0.1, 0.4, -0.3),
('current-lowest-stock-price-compared-to-1-day-previous-low-average-percent-deviation', 0.4, 1000000, -0.8),

('current-stock-vol-compared-to-1-day-previous-vol-average-percent-deviation', -10000.0, -1.0, 1.0),
('current-stock-vol-compared-to-1-day-previous-vol-average-percent-deviation', -1.00, -0.70, 0.9),
('current-stock-vol-compared-to-1-day-previous-vol-average-percent-deviation', -0.70, -0.40, 0.8),
('current-stock-vol-compared-to-1-day-previous-vol-average-percent-deviation', -0.40, -0.20, 0.7),
('current-stock-vol-compared-to-1-day-previous-vol-average-percent-deviation', -0.20, -0.10, 0.6),
('current-stock-vol-compared-to-1-day-previous-vol-average-percent-deviation', -0.10, -0.05, 0.5),
('current-stock-vol-compared-to-1-day-previous-vol-average-percent-deviation', -0.05, -0.02, 0.4),
('current-stock-vol-compared-to-1-day-previous-vol-average-percent-deviation', -0.02, -0.01, 0.2),
('current-stock-vol-compared-to-1-day-previous-vol-average-percent-deviation', -0.01, 0.00, 0.1),
('current-stock-vol-compared-to-1-day-previous-vol-average-percent-deviation', 0.00, 0.05, -0.1),
('current-stock-vol-compared-to-1-day-previous-vol-average-percent-deviation', 0.05, 0.1, -0.2),
('current-stock-vol-compared-to-1-day-previous-vol-average-percent-deviation', 0.1, 0.2, -0.5),
('current-stock-vol-compared-to-1-day-previous-vol-average-percent-deviation', 0.2, 1000000, -1.0),

('current-stock-vol-compared-to-1-day-previous-vol-high-percent-deviation', -10000.0, -1.0, 1.0),
('current-stock-vol-compared-to-1-day-previous-vol-high-percent-deviation', -1.00, -0.70, 0.9),
('current-stock-vol-compared-to-1-day-previous-vol-high-percent-deviation', -0.70, -0.40, 0.8),
('current-stock-vol-compared-to-1-day-previous-vol-high-percent-deviation', -0.40, -0.20, 0.7),
('current-stock-vol-compared-to-1-day-previous-vol-high-percent-deviation', -0.20, -0.10, 0.6),
('current-stock-vol-compared-to-1-day-previous-vol-high-percent-deviation', -0.10, -0.05, 0.5),
('current-stock-vol-compared-to-1-day-previous-vol-high-percent-deviation', -0.05, -0.02, 0.4),
('current-stock-vol-compared-to-1-day-previous-vol-high-percent-deviation', -0.02, -0.01, 0.2),
('current-stock-vol-compared-to-1-day-previous-vol-high-percent-deviation', -0.01, 0.00, 0.1),
('current-stock-vol-compared-to-1-day-previous-vol-high-percent-deviation', 0.00, 0.05, -0.1),
('current-stock-vol-compared-to-1-day-previous-vol-high-percent-deviation', 0.05, 0.1, -0.2),
('current-stock-vol-compared-to-1-day-previous-vol-high-percent-deviation', 0.1, 0.2, -0.5),
('current-stock-vol-compared-to-1-day-previous-vol-high-percent-deviation', 0.2, 1000000, -1.0),

('current-stock-vol-compared-to-1-day-previous-vol-low-percent-deviation', -10000.0, -1.0, 1.0),
('current-stock-vol-compared-to-1-day-previous-vol-low-percent-deviation', -1.00, -0.70, 0.9),
('current-stock-vol-compared-to-1-day-previous-vol-low-percent-deviation', -0.70, -0.40, 0.8),
('current-stock-vol-compared-to-1-day-previous-vol-low-percent-deviation', -0.40, -0.20, 0.7),
('current-stock-vol-compared-to-1-day-previous-vol-low-percent-deviation', -0.20, -0.10, 0.6),
('current-stock-vol-compared-to-1-day-previous-vol-low-percent-deviation', -0.10, -0.05, 0.5),
('current-stock-vol-compared-to-1-day-previous-vol-low-percent-deviation', -0.05, -0.02, 0.4),
('current-stock-vol-compared-to-1-day-previous-vol-low-percent-deviation', -0.02, -0.01, 0.2),
('current-stock-vol-compared-to-1-day-previous-vol-low-percent-deviation', -0.01, 0.00, 0.1),
('current-stock-vol-compared-to-1-day-previous-vol-low-percent-deviation', 0.00, 0.05, -0.1),
('current-stock-vol-compared-to-1-day-previous-vol-low-percent-deviation', 0.05, 0.1, -0.2),
('current-stock-vol-compared-to-1-day-previous-vol-low-percent-deviation', 0.1, 0.2, -0.5),
('current-stock-vol-compared-to-1-day-previous-vol-low-percent-deviation', 0.2, 1000000, -1.0),

----------------------------------------------------------
--- 7 Days analyzers
----------------------------------------------------------
('current-stock-price-compared-to-7-days-previous-close-average-percent-deviation', -10000.0, -1.0, 1.0),
('current-stock-price-compared-to-7-days-previous-close-average-percent-deviation', -1.00, -0.70, 0.9),
('current-stock-price-compared-to-7-days-previous-close-average-percent-deviation', -0.70, -0.40, 0.8),
('current-stock-price-compared-to-7-days-previous-close-average-percent-deviation', -0.40, -0.20, 0.7),
('current-stock-price-compared-to-7-days-previous-close-average-percent-deviation', -0.20, -0.10, 0.6),
('current-stock-price-compared-to-7-days-previous-close-average-percent-deviation', -0.10, -0.05, 0.5),
('current-stock-price-compared-to-7-days-previous-close-average-percent-deviation', -0.05, -0.02, 0.4),
('current-stock-price-compared-to-7-days-previous-close-average-percent-deviation', -0.02, -0.01, 0.2),
('current-stock-price-compared-to-7-days-previous-close-average-percent-deviation', -0.01, 0.00, 0.1),
('current-stock-price-compared-to-7-days-previous-close-average-percent-deviation', 0.00, 0.05, -0.1),
('current-stock-price-compared-to-7-days-previous-close-average-percent-deviation', 0.05, 0.1, -0.2),
('current-stock-price-compared-to-7-days-previous-close-average-percent-deviation', 0.1, 0.2, -0.5),
('current-stock-price-compared-to-7-days-previous-close-average-percent-deviation', 0.2, 1000000, -1.0),

('current-stock-price-compared-to-7-days-previous-high-average-percent-deviation', -10000.0, -1.0, 1.0),
('current-stock-price-compared-to-7-days-previous-high-average-percent-deviation', -1.00, -0.70, 0.9),
('current-stock-price-compared-to-7-days-previous-high-average-percent-deviation', -0.70, -0.40, 0.8),
('current-stock-price-compared-to-7-days-previous-high-average-percent-deviation', -0.40, -0.20, 0.7),
('current-stock-price-compared-to-7-days-previous-high-average-percent-deviation', -0.20, -0.10, 0.6),
('current-stock-price-compared-to-7-days-previous-high-average-percent-deviation', -0.10, -0.05, 0.5),
('current-stock-price-compared-to-7-days-previous-high-average-percent-deviation', -0.05, -0.02, 0.4),
('current-stock-price-compared-to-7-days-previous-high-average-percent-deviation', -0.02, -0.01, 0.2),
('current-stock-price-compared-to-7-days-previous-high-average-percent-deviation', -0.01, 0.00, 0.1),
('current-stock-price-compared-to-7-days-previous-high-average-percent-deviation', 0.00, 0.05, -0.1),
('current-stock-price-compared-to-7-days-previous-high-average-percent-deviation', 0.05, 0.1, -0.2),
('current-stock-price-compared-to-7-days-previous-high-average-percent-deviation', 0.1, 0.2, -0.5),
('current-stock-price-compared-to-7-days-previous-high-average-percent-deviation', 0.2, 1000000, -1.0),

('current-stock-price-compared-to-7-days-previous-low-average-percent-deviation', -10000.0, -1.0, 1.0),
('current-stock-price-compared-to-7-days-previous-low-average-percent-deviation', -1.00, -0.70, 0.9),
('current-stock-price-compared-to-7-days-previous-low-average-percent-deviation', -0.70, -0.40, 0.8),
('current-stock-price-compared-to-7-days-previous-low-average-percent-deviation', -0.40, -0.20, 0.7),
('current-stock-price-compared-to-7-days-previous-low-average-percent-deviation', -0.20, -0.10, 0.6),
('current-stock-price-compared-to-7-days-previous-low-average-percent-deviation', -0.10, -0.05, 0.5),
('current-stock-price-compared-to-7-days-previous-low-average-percent-deviation', -0.05, -0.02, 0.4),
('current-stock-price-compared-to-7-days-previous-low-average-percent-deviation', -0.02, -0.01, 0.2),
('current-stock-price-compared-to-7-days-previous-low-average-percent-deviation', -0.01, 0.00, 0.1),
('current-stock-price-compared-to-7-days-previous-low-average-percent-deviation', 0.00, 0.05, -0.1),
('current-stock-price-compared-to-7-days-previous-low-average-percent-deviation', 0.05, 0.1, -0.2),
('current-stock-price-compared-to-7-days-previous-low-average-percent-deviation', 0.1, 0.2, -0.5),
('current-stock-price-compared-to-7-days-previous-low-average-percent-deviation', 0.2, 1000000, -1.0),

('current-stock-price-compared-to-7-days-previous-lowest-percent-deviation', -10000.0, -1.0, 1.0),
('current-stock-price-compared-to-7-days-previous-lowest-percent-deviation', -1.00, -0.30, 1.0),
('current-stock-price-compared-to-7-days-previous-lowest-percent-deviation', -0.30, -0.10, 0.5),
('current-stock-price-compared-to-7-days-previous-lowest-percent-deviation', -0.10, -0.001, 0.2),
('current-stock-price-compared-to-7-days-previous-lowest-percent-deviation', -0.001, 0.0, 0.1),
('current-stock-price-compared-to-7-days-previous-lowest-percent-deviation', 0.0, 0.1, -0.05),
('current-stock-price-compared-to-7-days-previous-lowest-percent-deviation', 0.1, 0.4, -0.4),
('current-stock-price-compared-to-7-days-previous-lowest-percent-deviation', 0.4, 1000000, -1.0),

('current-stock-price-compared-to-7-days-previous-highest-percent-deviation', -10000.0, -1.0, 1.0),
('current-stock-price-compared-to-7-days-previous-highest-percent-deviation', -1.00, -0.80, 1.0),
('current-stock-price-compared-to-7-days-previous-highest-percent-deviation', -0.80, 0.0, 0.1),
('current-stock-price-compared-to-7-days-previous-highest-percent-deviation', 0.0, 0.4, -0.6),
('current-stock-price-compared-to-7-days-previous-highest-percent-deviation', 0.4, 1000000, -1.0),

('current-lowest-stock-price-compared-to-7-days-previous-lowest-percent-deviation', -10000.0, -8.0, 1.0),
('current-lowest-stock-price-compared-to-7-days-previous-lowest-percent-deviation', -0.80, -0.3, 0.6),
('current-lowest-stock-price-compared-to-7-days-previous-lowest-percent-deviation', -0.3, 0.0, 0.4),
('current-lowest-stock-price-compared-to-7-days-previous-lowest-percent-deviation', 0.0, 0.1, -0.1),
('current-lowest-stock-price-compared-to-7-days-previous-lowest-percent-deviation', 0.1, 0.4, -0.3),
('current-lowest-stock-price-compared-to-7-days-previous-lowest-percent-deviation', 0.4, 1000000, -0.8),

('current-lowest-stock-price-compared-to-7-days-previous-low-average-percent-deviation', -10000.0, -8.0, 1.0),
('current-lowest-stock-price-compared-to-7-days-previous-low-average-percent-deviation', -0.80, -0.3, 0.6),
('current-lowest-stock-price-compared-to-7-days-previous-low-average-percent-deviation', -0.3, 0.0, 0.4),
('current-lowest-stock-price-compared-to-7-days-previous-low-average-percent-deviation', 0.0, 0.1, -0.1),
('current-lowest-stock-price-compared-to-7-days-previous-low-average-percent-deviation', 0.1, 0.4, -0.3),
('current-lowest-stock-price-compared-to-7-days-previous-low-average-percent-deviation', 0.4, 1000000, -0.8),

('current-stock-vol-compared-to-7-days-previous-vol-average-percent-deviation', -10000.0, -1.0, 1.0),
('current-stock-vol-compared-to-7-days-previous-vol-average-percent-deviation', -1.00, -0.70, 0.9),
('current-stock-vol-compared-to-7-days-previous-vol-average-percent-deviation', -0.70, -0.40, 0.8),
('current-stock-vol-compared-to-7-days-previous-vol-average-percent-deviation', -0.40, -0.20, 0.7),
('current-stock-vol-compared-to-7-days-previous-vol-average-percent-deviation', -0.20, -0.10, 0.6),
('current-stock-vol-compared-to-7-days-previous-vol-average-percent-deviation', -0.10, -0.05, 0.5),
('current-stock-vol-compared-to-7-days-previous-vol-average-percent-deviation', -0.05, -0.02, 0.4),
('current-stock-vol-compared-to-7-days-previous-vol-average-percent-deviation', -0.02, -0.01, 0.2),
('current-stock-vol-compared-to-7-days-previous-vol-average-percent-deviation', -0.01, 0.00, 0.1),
('current-stock-vol-compared-to-7-days-previous-vol-average-percent-deviation', 0.00, 0.05, -0.1),
('current-stock-vol-compared-to-7-days-previous-vol-average-percent-deviation', 0.05, 0.1, -0.2),
('current-stock-vol-compared-to-7-days-previous-vol-average-percent-deviation', 0.1, 0.2, -0.5),
('current-stock-vol-compared-to-7-days-previous-vol-average-percent-deviation', 0.2, 1000000, -1.0),

('current-stock-vol-compared-to-7-days-previous-vol-high-percent-deviation', -10000.0, -1.0, 1.0),
('current-stock-vol-compared-to-7-days-previous-vol-high-percent-deviation', -1.00, -0.70, 0.9),
('current-stock-vol-compared-to-7-days-previous-vol-high-percent-deviation', -0.70, -0.40, 0.8),
('current-stock-vol-compared-to-7-days-previous-vol-high-percent-deviation', -0.40, -0.20, 0.7),
('current-stock-vol-compared-to-7-days-previous-vol-high-percent-deviation', -0.20, -0.10, 0.6),
('current-stock-vol-compared-to-7-days-previous-vol-high-percent-deviation', -0.10, -0.05, 0.5),
('current-stock-vol-compared-to-7-days-previous-vol-high-percent-deviation', -0.05, -0.02, 0.4),
('current-stock-vol-compared-to-7-days-previous-vol-high-percent-deviation', -0.02, -0.01, 0.2),
('current-stock-vol-compared-to-7-days-previous-vol-high-percent-deviation', -0.01, 0.00, 0.1),
('current-stock-vol-compared-to-7-days-previous-vol-high-percent-deviation', 0.00, 0.05, -0.1),
('current-stock-vol-compared-to-7-days-previous-vol-high-percent-deviation', 0.05, 0.1, -0.2),
('current-stock-vol-compared-to-7-days-previous-vol-high-percent-deviation', 0.1, 0.2, -0.5),
('current-stock-vol-compared-to-7-days-previous-vol-high-percent-deviation', 0.2, 1000000, -1.0),

('current-stock-vol-compared-to-7-days-previous-vol-low-percent-deviation', -10000.0, -1.0, 1.0),
('current-stock-vol-compared-to-7-days-previous-vol-low-percent-deviation', -1.00, -0.70, 0.9),
('current-stock-vol-compared-to-7-days-previous-vol-low-percent-deviation', -0.70, -0.40, 0.8),
('current-stock-vol-compared-to-7-days-previous-vol-low-percent-deviation', -0.40, -0.20, 0.7),
('current-stock-vol-compared-to-7-days-previous-vol-low-percent-deviation', -0.20, -0.10, 0.6),
('current-stock-vol-compared-to-7-days-previous-vol-low-percent-deviation', -0.10, -0.05, 0.5),
('current-stock-vol-compared-to-7-days-previous-vol-low-percent-deviation', -0.05, -0.02, 0.4),
('current-stock-vol-compared-to-7-days-previous-vol-low-percent-deviation', -0.02, -0.01, 0.2),
('current-stock-vol-compared-to-7-days-previous-vol-low-percent-deviation', -0.01, 0.00, 0.1),
('current-stock-vol-compared-to-7-days-previous-vol-low-percent-deviation', 0.00, 0.05, -0.1),
('current-stock-vol-compared-to-7-days-previous-vol-low-percent-deviation', 0.05, 0.1, -0.2),
('current-stock-vol-compared-to-7-days-previous-vol-low-percent-deviation', 0.1, 0.2, -0.5),
('current-stock-vol-compared-to-7-days-previous-vol-low-percent-deviation', 0.2, 1000000, -1.0);


select * from analyzer_weights_v1;

